# Belajar fundamental tensor menggunakan TensorFlow

In [1]:
import datetime
print(f"Last Running Code : {datetime.date.today()}")

Last Running Code : 2023-10-13


In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(f"Tensorflow version : {tf.__version__}")

2023-10-13 11:23:55.161043: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-13 11:23:55.771576: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-13 11:23:55.771623: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-13 11:23:55.774850: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-13 11:23:56.096208: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-13 11:23:56.097955: I tensorflow/core/platform/cpu_feature_guard.cc:182] This Tens

Tensorflow version : 2.14.0


# 1. Creating Tensorflow with tf.constant()

## 1.1. Creating Scalar (0 Dimensi)

In [5]:
#  A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number).
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check dimensi
scalar.ndim

0

## 1.2. Creating Vector (1 Dimensi)

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check dimensi vector
vector.ndim

1

## 1.3. Creating Matrix ( >1 Dimensi)

In [7]:
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [8]:
# Check dimensi matrix
matrix.ndim

2

### 1.3.1. Create Matrix With specific data type using dtype parameter (default is int32 or float32)

In [9]:
matrix_dtype = tf.constant(
    [[23,43],[22,56]], 
    dtype=tf.float32 #spesifik type data
    )

matrix_dtype

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[23., 43.],
       [22., 56.]], dtype=float32)>

In [10]:
matrix_dtype.ndim

2

## 1.4. Creating Tensor (>2 Dimensi)

In [11]:
tensor = tf.constant([
    [[1,2,3,4],[34,54,23,77],[21,34,65,87]],
    [[34,45,56,234],[123,43,56,23],[56,34,54,56]]
    ])

tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[  1,   2,   3,   4],
        [ 34,  54,  23,  77],
        [ 21,  34,  65,  87]],

       [[ 34,  45,  56, 234],
        [123,  43,  56,  23],
        [ 56,  34,  54,  56]]], dtype=int32)>

In [12]:
tensor.ndim

3

# 2. Creating tensor with tf.Variable()
berbeda dengan tf.constant, tf.Variable bersifat mutable (bisa diubah nilainya)

In [13]:
scalar = tf.Variable([0]) # Scalar
scalar

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([0], dtype=int32)>

In [14]:
vector = tf.Variable([2,4]) # Vector
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 4], dtype=int32)>

**Akan terjadi error jika tensor constant di ubah**

In [15]:
constant = tf.constant([2,3])
constant[0] = 3

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

**tetapi dengan tensor varible tidak. Namun perlu di ingat untuk mengganti nilai pada tensor harus menggunakan method assign()**

In [ ]:
varible = tf.Variable([2,3])
# Mengubah nilai seperti dibawah ini akan menghasillkan error
varible[0] = 3
varible

In [ ]:
# Berikut cara yang benar menggunakan assignn()
varible = tf.Variable([2,3])
varible[0].assign(3)
varible

**tensor constant tidak diubah wwalaupun menggunakan method assign()**

In [ ]:
constant = tf.constant([2,3])
constant[0].assign(3)
constant

# 3. Creating Random Tensor
Kenapa perlu membuat random tensor? karena pada awal pembelajaran neural network, selalu dimulai dari pola acak

## Using tf.random.Generator
pada proses ini sebenarnya yang digunakan adalah pseudorandom

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

In [ ]:
# Pada kodingan ini, nilainya akan selalu berubah dan tidak akan sama walaupun sudah di beri nilai seed
# Hal ini terjadi karena seed disini hanya bersifat operation seed dan bukan global seed karena itu setiap operasi akan menghasilkan nilai berbeda
not_suffled = tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_suffled, seed=42)

**Rule #4 tf.random.set_seed() "4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."** 
*Sebab, "Operasi yang mengandalkan benih acak sebenarnya berasal dari dua benih: benih global dan benih tingkat operasi. Ini yang menentukan benih global."*

In [ ]:
# DIsini nilai global seed diatur sehingga nilainya pseudorandom akan selalu sama
# untuk mengatur global seed
tf.random.set_seed(42)

#untuk mengatur seed pada area operasi saja
tf.random.shuffle(not_suffled, seed=42)

# 4. Cara lain membuat Tensors

## 4.1. Tensor Ones tf.ones()

In [ ]:
ones = tf.ones(shape=(3,4))
ones

## 4.2. Tensor Zeros tf.zeros()

In [ ]:
zeros = tf.zeros([3,4])
zeros

# 5. Mengubah Numpy Array menjadi Tensor

In [ ]:
import numpy as np
np_array = np.arange(1,25, dtype=np.int32)
tensor_from_np = tf.constant(np_array, shape=[2,3,4])

tensor_from_np

# 6. Memperoleh Informasi Dari Tensor

In [ ]:
#membuat array 4 dimensi
d4_tensor = tf.zeros([2,3,4,5])
d4_tensor

## 6.1. Mengambil Informasi menggunakan .shape .ndim tf.size()

In [ ]:
d4_tensor.shape, d4_tensor.ndim, tf.size(d4_tensor)

## 6.2. Get various attributes of tensor

In [ ]:
print("Data tipe dari tensor : ", d4_tensor.dtype)
print("Dimensi dari tensor : ",d4_tensor.ndim)
print("Shape dari Tensor : ",d4_tensor.shape)
print("Axis pertama dari tensor (2,3,4,5 maka axis pertamanya adalah 2):",d4_tensor.shape[0])
print("Axis terakhir dari tensor : ",d4_tensor.shape[-1])
print("Total element dari Tensor : ",tf.size(d4_tensor).numpy())

In [ ]:
# get the first 2 items of each dimension
d4_tensor[:2,:2,:2,:2]

In [ ]:
# mengambil selulruh kolom bari pertama dari baris 1 dimensi ke 3 dan baris 1 dari dimensi ke 4
d4_tensor[:1,:1,:1,:]

In [ ]:
d2_tensor = tf.constant([[1,2],[3,4]])
d2_tensor[:,1] # mengambil kolom 1 dari semua baris

## 6.3. Menambahkan dimensi

In [ ]:
# menambahkan dimensi menggunakan tf.newaxis
d3_tensor = d2_tensor[..., tf.newaxis]
d2_tensor, d3_tensor

In [ ]:
# menambahkan dimensi menggunakan tf.expand_dims
tf.expand_dims(d2_tensor, axis=-1) #-1 artinya axis terakhir

# 7. Memanipulasi Tensor

## 7.1. Operasi dasar

In [ ]:
d2_tensor = tf.Variable([[1,2],[3,4]])
d2_tensor + 10, d2_tensor*10, d2_tensor/2, d2_tensor**2

In [ ]:
#Perkalian Matrix dengan Konstanta
tf.multiply(d2_tensor, 10)

In [ ]:
# Perkalian Matrix dengan matrix
tf.matmul(d2_tensor, d2_tensor)

## 7.2. Manipulasi ukuran tensor dengan tf.reshape() dan tf.transpose()

In [ ]:
x = tf.constant([[1,2,3],[2,3,4]]) #tensor 2x3
y = tf.constant([[4,5,6],[6,7,8]]) #tensor 2x3
x, y

In [ ]:
# tensor 2x3 tidak bisa dikali dengan tensor 2x3
# 2x3 harus dikali 3x2 maka di reshape
x_reshape = tf.reshape(x, (3,2))
x_reshape

In [ ]:
# Maka sekarang dapat di kali
x_reshape @ y

## 7.3. Operasi Dot Matrix

In [ ]:
a = tf.Variable([
    [23,4,5],
    [23,54,23]
    ])

b = tf.Variable([
    [43,23,54],
    [4,7,8]
])

# menggunakan dot (.) dan transpose
c = tf.tensordot(a, tf.transpose(b), axes=1)

# Menggunakan matmul dan reshape
d = tf.matmul(tf.reshape(a, shape=(3,2)), b)

#nb : Transpose dan reshape tidak membentuk matrix yang sama saat mengubah matrix yang sama
c, d

## 7.4. Mengganti tipe data Tensor menggunakan tf.cast()

In [ ]:
np_a = np.arange(1,25)
mat_a = tf.constant(np_a, shape=(6,4))
mat_a, mat_a.dtype

In [ ]:
mat_a = tf.cast(mat_a, dtype=tf.float32)
mat_a, mat_a.dtype

## 7.5. Mengambil nilai absolute menggunakan tf.abs()

In [ ]:
b_mat = tf.constant(np.arange(-17,-1, dtype=np.int32), shape=(4,4))
b_mat

In [ ]:
# Mengambil nilai absolute
b_mat_abs = tf.abs(b_mat)
b_mat_abs

## 7.6. Mencari nilai min max mean sum (agregari) pada tensor
menggunakan tf.reduce_min(), tf.reduce_max(), tf.reduce_mean(), tf.reduce_sum

In [ ]:
tensor_mat = tf.constant(np.random.randint(low=5, high=200, size=72))
tensor_mat

In [ ]:
# min
tf.reduce_min(tensor_mat)

In [ ]:
# max
tf.reduce_max(tensor_mat)

In [ ]:
# mean
tf.reduce_mean(tensor_mat)

In [ ]:
# sum
tf.reduce_sum(tensor_mat)

In [ ]:
# standart devisasi
mat = tf.reshape(tensor_mat, shape=(8,9))
mat = tf.cast(mat, dtype=tf.float32)
tf.math.reduce_std(mat)

In [ ]:
# variance
tf.math.reduce_variance(mat)

## 7.7 Mengambil index max dan min

In [8]:
np.random.seed(42)
np_mat = np.random.uniform(low=12, high=99, size=(2,3,3))
mat = tf.constant(np_mat)
mat

<tf.Tensor: shape=(2, 3, 3), dtype=float64, numpy=
array([[[44.58499034, 94.71214466, 75.68347294],
        [64.08328813, 25.57362172, 25.57152327],
        [17.05327426, 87.35732468, 64.29700602]],

       [[73.60231427, 13.790851  , 96.38215714],
        [84.42250975, 30.47350263, 27.81877215],
        [27.95619236, 38.46907514, 57.65380955]]])>

In [10]:
# argmax
index_max = tf.argmax(mat)
index_max

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 0, 1],
       [1, 1, 1],
       [1, 0, 0]])>

In [11]:
# argmin
index_min = tf.argmin(mat)
index_min

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[0, 1, 0],
       [0, 0, 0],
       [0, 1, 1]])>

## 7.8 Squeezing tensor tf.squeeze()

In [3]:
np_mat_s = np.random.randint(low=8, high=99, size=(1,1,1,3,4))
t_w_singleD = tf.constant(np_mat_s)
t_w_singleD

<tf.Tensor: shape=(1, 1, 1, 3, 4), dtype=int64, numpy=
array([[[[[18,  9, 32, 46],
          [57, 36, 59, 46],
          [79, 24, 78, 30]]]]])>

In [4]:
squeeze_mat = tf.squeeze(t_w_singleD)
squeeze_mat

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[18,  9, 32, 46],
       [57, 36, 59, 46],
       [79, 24, 78, 30]])>

## 7.9 One Hot Encoding tf.one_hot()

In [33]:
label = [1,2,3]
label

[1, 2, 3]

In [35]:
a = tf.one_hot(label, depth=4)
a

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

## 7.9 Squaring, log, square root tf.square() tf.sqrt() tf.math.log()

In [38]:
nrand = np.random.randint(low=4, high=99, size=(4,3))
nrand

array([[93, 92, 52],
       [24, 62, 20],
       [ 9, 82, 78],
       [59, 92, 85]])

In [44]:
tf.square(nrand), tf.sqrt(tf.cast(nrand, dtype=tf.float32)), tf.math.log(tf.cast(nrand, dtype=tf.float32))

(<tf.Tensor: shape=(4, 3), dtype=int64, numpy=
 array([[8649, 8464, 2704],
        [ 576, 3844,  400],
        [  81, 6724, 6084],
        [3481, 8464, 7225]])>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[9.643651 , 9.591663 , 7.2111025],
        [4.8989797, 7.8740077, 4.472136 ],
        [3.       , 9.055386 , 8.83176  ],
        [7.6811457, 9.591663 , 9.219544 ]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[4.5325994, 4.5217886, 3.9512436],
        [3.1780539, 4.1271343, 2.9957323],
        [2.1972246, 4.406719 , 4.356709 ],
        [4.0775375, 4.5217886, 4.4426513]], dtype=float32)>)

# 8 Manipulasi tf.Variable

## 8.1.  tf.assign() tf.add_assign()

In [50]:
n = np.zeros(shape=(3,4))
tnsr = tf.Variable(n)

# .assign ==> mengubah nilai
a = tnsr.assign([
    [23,22,2,1],
    [12,4,2,5],
    [55,354,47,2]
])

# assign_add ==> menambahkan nilai ke dalam tensor (dimesi harus sama)
b = a.assign_add([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])
b

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float64, numpy=
array([[ 25.,  24.,   4.,   3.],
       [ 14.,   6.,   4.,   7.],
       [ 57., 356.,  49.,   4.]])>

# Exercises

## 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [51]:
vector = tf.constant(
    [12]
)

scalar = tf.constant(
    [12,12]
)

matrix = tf.constant(
    np.random.randint(23,99, size=(3,3))
)

tensor = tf.constant(
    np.arange(0,100,2), shape=(2,5,5)
)

vector, scalar, matrix, tensor

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([12], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 12], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int64, numpy=
 array([[45, 90, 94],
        [68, 80, 69],
        [62, 65, 66]])>,
 <tf.Tensor: shape=(2, 5, 5), dtype=int64, numpy=
 array([[[ 0,  2,  4,  6,  8],
         [10, 12, 14, 16, 18],
         [20, 22, 24, 26, 28],
         [30, 32, 34, 36, 38],
         [40, 42, 44, 46, 48]],
 
        [[50, 52, 54, 56, 58],
         [60, 62, 64, 66, 68],
         [70, 72, 74, 76, 78],
         [80, 82, 84, 86, 88],
         [90, 92, 94, 96, 98]]])>)

## 2. Find the shape, rank and size of the tensors you created in 1

In [56]:
scalar.shape, matrix.ndim, tf.size(tensor)

(TensorShape([2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

## 3. Create two tensors containing random values between 0 and 1 with shape [5, 300]

In [58]:
tnsr1 = tf.random.uniform(minval=0, maxval=1, shape=(5,300))
tnsr2 = tf.random.shuffle(tnsr1)
tnsr1, tnsr2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.5184852 , 0.76776004, 0.19462967, ..., 0.02660501, 0.86674345,
         0.20779896],
        [0.4517063 , 0.23947763, 0.28048515, ..., 0.52728033, 0.14744663,
         0.13690078],
        [0.30554235, 0.07899129, 0.52359474, ..., 0.70501924, 0.18861568,
         0.04344428],
        [0.78475845, 0.16142976, 0.801242  , ..., 0.8473673 , 0.19242013,
         0.18183768],
        [0.96092653, 0.71340096, 0.824124  , ..., 0.9448885 , 0.63093495,
         0.3247168 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.4517063 , 0.23947763, 0.28048515, ..., 0.52728033, 0.14744663,
         0.13690078],
        [0.78475845, 0.16142976, 0.801242  , ..., 0.8473673 , 0.19242013,
         0.18183768],
        [0.96092653, 0.71340096, 0.824124  , ..., 0.9448885 , 0.63093495,
         0.3247168 ],
        [0.30554235, 0.07899129, 0.52359474, ..., 0.70501924, 0.18861568,
         0.04344428],
        [0.51848

## 4. Multiply the two tensors you created in 3 using matrix multiplication

In [60]:
tensor_c = tf.multiply(tnsr1, tnsr2)
tensor_c

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.23420303, 0.18386136, 0.05459073, ..., 0.0140283 , 0.12779841,
        0.02844784],
       [0.35448033, 0.03865882, 0.22473648, ..., 0.4468001 , 0.0283717 ,
        0.02489372],
       [0.29360375, 0.05635247, 0.431507  , ..., 0.6661646 , 0.11900423,
        0.01410709],
       [0.23977694, 0.01275155, 0.4195261 , ..., 0.59741026, 0.03629345,
        0.00789981],
       [0.49822617, 0.54772073, 0.16039898, ..., 0.02513877, 0.5468587 ,
        0.06747581]], dtype=float32)>

## 5. Multiply the two tensors you created in 3 using dot product

In [64]:
tensor_d = tf.tensordot(tnsr1, tf.transpose(tnsr2), axes=1)
tensor_d

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 76.31357 ,  76.68758 ,  80.46172 ,  77.39366 , 105.083405],
       [ 95.221436,  69.576195,  75.95989 ,  74.01396 ,  76.31357 ],
       [ 74.01396 ,  72.00621 ,  75.46709 ,  98.23166 ,  77.39366 ],
       [ 69.576195,  97.43059 ,  78.9886  ,  72.00621 ,  76.68758 ],
       [ 75.95989 ,  78.9886  , 103.47169 ,  75.46709 ,  80.46172 ]],
      dtype=float32)>

## 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3]

In [65]:
tnsr3 = tf.random.uniform(minval=0, maxval=1, dtype=tf.float32, shape=(224,224,3))
tnsr3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[3.09707999e-01, 4.98467445e-01, 7.18839884e-01],
        [5.82867026e-01, 4.06065464e-01, 2.06283569e-01],
        [8.50550413e-01, 3.66299152e-01, 4.28361058e-01],
        ...,
        [7.59097934e-01, 3.81611109e-01, 6.61462665e-01],
        [3.62899899e-01, 7.47732043e-01, 4.45638537e-01],
        [9.46474910e-01, 2.40704298e-01, 7.97748566e-04]],

       [[9.29587722e-01, 1.22186303e-01, 7.14314342e-01],
        [5.55838227e-01, 6.10901713e-01, 1.21644616e-01],
        [9.08449173e-01, 7.81529188e-01, 3.04618478e-01],
        ...,
        [3.58580589e-01, 2.59028196e-01, 5.34951687e-02],
        [9.44876671e-03, 7.52988815e-01, 2.03812718e-01],
        [8.34198236e-01, 6.32038474e-01, 6.19304538e-01]],

       [[2.82387853e-01, 3.55593443e-01, 9.19523239e-02],
        [9.33130026e-01, 4.01654124e-01, 9.49791193e-01],
        [8.02042484e-02, 4.00134444e-01, 3.09573412e-01],
        ...,
        [9.06005621e-01, 3.52828

## 7. Find the min and max values of the tensor you created in 6

In [66]:
tensor_min = tf.reduce_min(tnsr3)
tensor_max = tf.reduce_max(tnsr3)

tensor_min, tensor_max

(<tf.Tensor: shape=(), dtype=float32, numpy=1.1086464e-05>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999951>)

## 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]

In [68]:
tnsr4 = tf.random.normal(shape=(1,224,224,3))
tnsr4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[ 7.27663636e-01, -5.60822606e-01,  1.85686302e+00],
         [ 1.66013062e+00,  3.33431140e-02,  1.01633072e+00],
         [-2.47482315e-01,  1.55798659e-01,  1.87620902e+00],
         ...,
         [ 8.33734274e-01, -8.62811953e-02, -4.75380391e-01],
         [-1.24498355e+00,  4.66777712e-01,  7.09739387e-01],
         [ 1.92770451e-01,  2.06973720e+00, -1.20759404e+00]],

        [[-8.98571491e-01, -1.85575914e+00,  6.77245736e-01],
         [-1.14836490e+00,  2.78509468e-01, -9.71903980e-01],
         [ 2.20580086e-01, -2.49833986e-01,  3.07049125e-01],
         ...,
         [-7.43755162e-01,  2.46512160e-01,  8.15746468e-03],
         [ 1.39643097e+00, -2.77630782e+00, -1.05003703e+00],
         [ 1.22110355e+00,  8.19301724e-01,  1.26787686e+00]],

        [[ 3.71297747e-01,  7.52032995e-01, -1.03006676e-01],
         [ 2.39627451e-01, -1.88935852e+00, -1.39815316e-01],
         [-1.04455702e-01,  1.30994713e+00

In [74]:
squeezed = tf.squeeze(tnsr4, axis=0)
squeezed.shape

TensorShape([224, 224, 3])

## 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value

In [87]:
tnsr5 = tf.random.normal(shape=(10,))
tnsr5

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.13019317, -0.5366344 , -1.1019168 ,  1.7443868 ,  0.7857995 ,
        0.46997228,  0.23263977, -0.2594993 , -0.946326  , -1.08339   ],
      dtype=float32)>

In [88]:
ind_max = tf.argmax(tnsr5)
ind_max

<tf.Tensor: shape=(), dtype=int64, numpy=3>

## 10. One-hot encode the tensor you created in 9

In [91]:
oh_tensor = tf.one_hot(tf.cast(tnsr5, dtype=tf.int32), depth=10)
oh_tensor

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>