# Belajar fundamental tensor menggunakan TensorFlow

In [16]:
import datetime
print(f"Last Running Code : {datetime.date.today()}")

Last Running Code : 2023-09-28


In [17]:
import tensorflow as tf
print(f"Tensorflow version : {tf.__version__}")

Tensorflow version : 2.13.0


# 1. Creating Tensorflow with tf.constant()

## 1.1. Creating Scalar (0 Dimensi)

In [18]:
#  A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number).
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [19]:
# check dimensi
scalar.ndim

0

## 1.2. Creating Vector (1 Dimensi)

In [20]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [21]:
# Check dimensi vector
vector.ndim

1

## 1.3. Creating Matrix ( >1 Dimensi)

In [22]:
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [23]:
# Check dimensi matrix
matrix.ndim

2

### 1.3.1. Create Matrix With specific data type using dtype parameter (default is int32 or float32)

In [24]:
matrix_dtype = tf.constant(
    [[23,43],[22,56]], 
    dtype=tf.float32 #spesifik type data
    )

matrix_dtype

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[23., 43.],
       [22., 56.]], dtype=float32)>

In [25]:
matrix_dtype.ndim

2

## 1.4. Creating Tensor (>2 Dimensi)

In [26]:
tensor = tf.constant([
    [[1,2,3,4],[34,54,23,77],[21,34,65,87]],
    [[34,45,56,234],[123,43,56,23],[56,34,54,56]]
    ])

tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[  1,   2,   3,   4],
        [ 34,  54,  23,  77],
        [ 21,  34,  65,  87]],

       [[ 34,  45,  56, 234],
        [123,  43,  56,  23],
        [ 56,  34,  54,  56]]], dtype=int32)>

In [27]:
tensor.ndim

3

# 2. Creating tensor with tf.Variable()
berbeda dengan tf.constant, tf.Variable bersifat mutable (bisa diubah nilainya)

In [28]:
scalar = tf.Variable([0]) # Scalar
scalar

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([0], dtype=int32)>

In [29]:
vector = tf.Variable([2,4]) # Vector
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 4], dtype=int32)>

**Akan terjadi error jika tensor constant di ubah**

In [30]:
constant = tf.constant([2,3])
constant[0] = 3

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

**tetapi dengan tensor varible tidak. Namun perlu di ingat untuk mengganti nilai pada tensor harus menggunakan method assign()**

In [ ]:
varible = tf.Variable([2,3])
# Mengubah nilai seperti dibawah ini akan menghasillkan error
varible[0] = 3
varible

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# Berikut cara yang benar menggunakan assignn()
varible = tf.Variable([2,3])
varible[0].assign(3)
varible

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3], dtype=int32)>

**tensor constant tidak diubah wwalaupun menggunakan method assign()**

In [ ]:
constant = tf.constant([2,3])
constant[0].assign(3)
constant

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# 3. Creating Random Tensor
Kenapa perlu membuat random tensor? karena pada awal pembelajaran neural network, selalu dimulai dari pola acak

## Using tf.random.Generator
pada proses ini sebenarnya yang digunakan adalah pseudorandom

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# Pada kodingan ini, nilainya akan selalu berubah dan tidak akan sama walaupun sudah di beri nilai seed
# Hal ini terjadi karena seed disini hanya bersifat operation seed dan bukan global seed karena itu setiap operasi akan menghasilkan nilai berbeda
not_suffled = tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_suffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

**Rule #4 tf.random.set_seed() "4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."** 
*Sebab, "Operasi yang mengandalkan benih acak sebenarnya berasal dari dua benih: benih global dan benih tingkat operasi. Ini yang menentukan benih global."*

In [ ]:
# DIsini nilai global seed diatur sehingga nilainya pseudorandom akan selalu sama
# untuk mengatur global seed
tf.random.set_seed(42)

#untuk mengatur seed pada area operasi saja
tf.random.shuffle(not_suffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# 4. Cara lain membuat Tensors

## 4.1. Tensor Ones tf.ones()

In [ ]:
ones = tf.ones(shape=(3,4))
ones

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

## 4.2. Tensor Zeros tf.zeros()

In [ ]:
zeros = tf.zeros([3,4])
zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# 5. Mengubah Numpy Array menjadi Tensor

In [37]:
import numpy as np
np_array = np.arange(1,25, dtype=np.int32)
tensor_from_np = tf.constant(np_array, shape=[2,3,4])

tensor_from_np

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# 6. Memperoleh Informasi Dari Tensor

In [ ]:
#membuat array 4 dimensi
d4_tensor = tf.zeros([2,3,4,5])
d4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

## 6.1. Mengambil Informasi menggunakan .shape .ndim tf.size()

In [ ]:
d4_tensor.shape, d4_tensor.ndim, tf.size(d4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

## 6.2. Get various attributes of tensor

In [ ]:
print("Data tipe dari tensor : ", d4_tensor.dtype)
print("Dimensi dari tensor : ",d4_tensor.ndim)
print("Shape dari Tensor : ",d4_tensor.shape)
print("Axis pertama dari tensor (2,3,4,5 maka axis pertamanya adalah 2):",d4_tensor.shape[0])
print("Axis terakhir dari tensor : ",d4_tensor.shape[-1])
print("Total element dari Tensor : ",tf.size(d4_tensor).numpy())

Data tipe dari tensor :  <dtype: 'float32'>
Dimensi dari tensor :  4
Shape dari Tensor :  (2, 3, 4, 5)
Axis pertama dari tensor (2,3,4,5 maka axis pertamanya adalah 2): 2
Axis terakhir dari tensor :  5
Total element dari Tensor :  120


In [ ]:
# get the first 2 items of each dimension
d4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# mengambil selulruh kolom bari pertama dari baris 1 dimensi ke 3 dan baris 1 dari dimensi ke 4
d4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
d2_tensor = tf.constant([[1,2],[3,4]])
d2_tensor[:,1] # mengambil kolom 1 dari semua baris

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

## 6.3. Menambahkan dimensi

In [ ]:
# menambahkan dimensi menggunakan tf.newaxis
d3_tensor = d2_tensor[..., tf.newaxis]
d2_tensor, d3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[1],
         [2]],
 
        [[3],
         [4]]], dtype=int32)>)

In [ ]:
# menambahkan dimensi menggunakan tf.expand_dims
tf.expand_dims(d2_tensor, axis=-1) #-1 artinya axis terakhir

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

# 7. Memanipulasi Tensor

## 7.1. Operasi dasar

In [ ]:
d2_tensor = tf.Variable([[1,2],[3,4]])
d2_tensor + 10, d2_tensor*10, d2_tensor/2, d2_tensor**2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 12],
        [13, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[0.5, 1. ],
        [1.5, 2. ]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 1,  4],
        [ 9, 16]], dtype=int32)>)

In [ ]:
#Perkalian Matrix dengan Konstanta
tf.multiply(d2_tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
# Perkalian Matrix dengan matrix
tf.matmul(d2_tensor, d2_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

## 7.2. Manipulasi ukuran tensor dengan tf.reshape() dan tf.transpose()

In [ ]:
x = tf.constant([[1,2,3],[2,3,4]]) #tensor 2x3
y = tf.constant([[4,5,6],[6,7,8]]) #tensor 2x3
x, y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [2, 3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[4, 5, 6],
        [6, 7, 8]], dtype=int32)>)

In [ ]:
# tensor 2x3 tidak bisa dikali dengan tensor 2x3
# 2x3 harus dikali 3x2 maka di reshape
x_reshape = tf.reshape(x, (3,2))
x_reshape

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Maka sekarang dapat di kali
x_reshape @ y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16, 19, 22],
       [24, 29, 34],
       [36, 43, 50]], dtype=int32)>

## 7.3. Operasi Dot Matrix

In [35]:
a = tf.Variable([
    [23,4,5],
    [23,54,23]
    ])

b = tf.Variable([
    [43,23,54],
    [4,7,8]
])

# menggunakan dot (.) dan transpose
c = tf.tensordot(a, tf.transpose(b), axes=1)

# Menggunakan matmul dan reshape
d = tf.matmul(tf.reshape(a, shape=(3,2)), b)

#nb : Transpose dan reshape tidak membentuk matrix yang sama saat mengubah matrix yang sama
c, d

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1351,  160],
        [3473,  654]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1005,  557, 1274],
        [ 307,  276,  454],
        [2414, 1403, 3100]], dtype=int32)>)

## 7.4. Mengganti tipe data Tensor menggunakan tf.cast()

In [49]:
np_a = np.arange(1,25)
mat_a = tf.constant(np_a, shape=(6,4))
mat_a, mat_a.dtype

(<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])>,
 tf.int64)

In [51]:
mat_a = tf.cast(mat_a, dtype=tf.float32)
mat_a, mat_a.dtype

(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]], dtype=float32)>,
 tf.float32)

## 7.5. Mengambil nilai absolute menggunakan tf.abs()

In [53]:
b_mat = tf.constant(np.arange(-17,-1, dtype=np.int32), shape=(4,4))
b_mat

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[-17, -16, -15, -14],
       [-13, -12, -11, -10],
       [ -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2]], dtype=int32)>

In [54]:
# Mengambil nilai absolute
b_mat_abs = tf.abs(b_mat)
b_mat_abs

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[17, 16, 15, 14],
       [13, 12, 11, 10],
       [ 9,  8,  7,  6],
       [ 5,  4,  3,  2]], dtype=int32)>

## 7.6. Mencari nilai min max mean sum (agregari) pada tensor
menggunakan tf.reduce_min(), tf.reduce_max(), tf.reduce_mean(), tf.reduce_sum

In [55]:
tensor_mat = tf.constant(np.random.randint(low=5, high=200, size=72))
tensor_mat

<tf.Tensor: shape=(72,), dtype=int64, numpy=
array([ 66, 159, 100, 192, 120, 100,  27,  89,  98, 117, 154, 113,  12,
        10,  72,  23,  67,  86, 110,  24, 190, 112, 199,  28,  79, 198,
        46,  59, 179, 142, 145,  48,  46, 188,  36,  57,  26,  55, 172,
       152, 169, 189,  58,  31,  98, 139, 136, 161,  10, 129, 116,  20,
       143, 168, 104,  42,  89, 106,  40, 123, 103,  10,  97, 191, 194,
       115, 174,  61,  55, 148, 138, 175])>

In [56]:
# min
tf.reduce_min(tensor_mat)

<tf.Tensor: shape=(), dtype=int64, numpy=10>

In [58]:
# max
tf.reduce_max(tensor_mat)

<tf.Tensor: shape=(), dtype=int64, numpy=199>

In [59]:
# mean
tf.reduce_mean(tensor_mat)

<tf.Tensor: shape=(), dtype=int64, numpy=103>

In [60]:
# sum
tf.reduce_sum(tensor_mat)

<tf.Tensor: shape=(), dtype=int64, numpy=7428>

In [65]:
# standart devisasi
mat = tf.reshape(tensor_mat, shape=(8,9))
mat = tf.cast(mat, dtype=tf.float32)
tf.math.reduce_std(mat)

<tf.Tensor: shape=(), dtype=float32, numpy=56.919044>

In [66]:
# variance
tf.math.reduce_variance(mat)

<tf.Tensor: shape=(), dtype=float32, numpy=3239.7778>