In [1]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 489.8/489.8 MB 1.7 MB/s eta 0:00:0000:0100:05
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 KB 3.3 MB/s eta 0:00:00a 0:00:01
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached libclang-16.0.6-py2.py3-none-manylinux2010_x86_64.whl (22.9 MB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 3.2 MB/s eta 0:00:0000:0100:01
  Using cached wrapt-1.14.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.6/311.6 KB 3.2 MB/s eta 0:00:00a 0:00:01
  Using cached tensorflow_io_gcs_filesystem-0.34.0-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
  Using cached h5py-3.9.0-cp310-cp310-manylinux_2

In [5]:
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 2.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.7/301.7 KB 2.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 2.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 2.1 MB/s eta 0:00:0000:0100:01


In [3]:
import datetime
print(f"Last running code at {datetime.date.today()}")

Last running code at 2023-10-06


In [6]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [11]:
tf.random.set_seed(42)
X = tf.constant(tf.random.normal(shape=(12,)))
y = tf.constant(X*4)
X,y

(<tf.Tensor: shape=(12,), dtype=float32, numpy=
 array([ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 , -2.3880599 ,
        -1.0392479 , -0.5573232 ,  0.539707  ,  1.6994323 ,  0.28893656,
        -1.5066116 , -0.26454744], dtype=float32)>,
 <tf.Tensor: shape=(12,), dtype=float32, numpy=
 array([ 1.309874 , -3.3705032,  1.2777348, -5.6302075, -9.552239 ,
        -4.1569915, -2.2292929,  2.158828 ,  6.797729 ,  1.1557462,
        -6.0264463, -1.0581897], dtype=float32)>)

In [12]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1)
])

In [13]:
model.compile(
    loss=tf.losses.mae,
    optimizer=tf.optimizers.SGD(),
    metrics=['mae']
    )

In [19]:
model.fit(tf.expand_dims(X, axis=-1), y, epochs=20, verbose=5)

Epoch 1/20
Epoch 2/20
Epoch 3/20
Epoch 4/20
Epoch 5/20
Epoch 6/20
Epoch 7/20
Epoch 8/20


Epoch 9/20
Epoch 10/20
Epoch 11/20
Epoch 12/20
Epoch 13/20
Epoch 14/20
Epoch 15/20
Epoch 16/20
Epoch 17/20
Epoch 18/20
Epoch 19/20
Epoch 20/20


In [15]:
model.predict([12])

1/1 [==============================] - 0s 96ms/step


array([[7.51744]], dtype=float32)

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2 (8.00 Byte)
Trainable params: 2 (8.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
